[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["heic-convert"]
  included_files = ["node_modules/heic-convert/**/*"]
  timeout = 30

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200