[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["heic-convert", "cloudinary"]
  included_files = ["node_modules/heic-convert/**/*"]

[functions.processImages]
  timeout = 30

[functions.saveGallery]
  timeout = 10

[functions.processImages.environment]
  CLOUDINARY_CLOUD_NAME = "dtn8ucfqp"
  CLOUDINARY_API_KEY = "744838263679319"
  CLOUDINARY_API_SECRET = "Wwro_3-wpEa2UQuHTlDVikgX_5E"